alarm_rules:
  - id: high_temp
    enabled: true
    when:
      sensor_id: temp
      op: ">"
      value: 60
    then:
      - type: log
        level: warn
        message: "temperature high"

  - id: high_humi
    enabled: true
    when:
      sensor_id: humi
      op: ">"
      value: 80
    then:
      - type: log
        level: warn
        message: "humidity high"
