automation_rules:
  - id: cooling_on
    enabled: true
    when:
      sensor_id: temp
      op: ">"
      value: 55
    then:
      - type: actuator_set
        actuator_id: motor
        value: '{"type":"control","payload":{"motor_on":1,"motor_sp":30,"motor_dir":0}}'

  - id: cooling_off
    enabled: true
    when:
      sensor_id: temp
      op: "<"
      value: 50
    then:
      - type: actuator_set
        actuator_id: motor
        value: '{"type":"control","payload":{"motor_on":0}}'
