name: IotEdgeGateway
env: development

paths:
  www_root: www
  log_file: data/logs/iotgw-dev.log

logging:
  level: info

network:
  http_api:
    host: 0.0.0.0
    port: 8081

mqtt:
  enabled: true
  broker_host: "127.0.0.1"
  broker_port: 1884
  client_id: iotgw-dev
  username: ""
  password: ""
  keepalive_sec: 30
  clean_session: true
  topic_prefix: "iotgw/dev/"

camera:
  device: "/dev/video0"
